SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';

flush privileges;

DROP DATABASE IF EXISTS hnretail;
CREATE DATABASE hnretail;
USE hnretail;


CREATE TABLE item( 
Item_id int (4) UNSIGNED NOT NULL AUTO_INCREMENT,
Item_name VARCHAR (50) NOT NULL,
Item_desc VARCHAR (50) NOT NULL,
Item_quantity int (3) NOT NULL,
PRIMARY KEY (Item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contents(
Cont_id int (4) UNSIGNED NOT NULL AUTO_INCREMENT,
Item_id int (4) UNSIGNED NOT NULL,
Quantity int (3) NOT NULL,
PRIMARY KEY (Cont_id),
FOREIGN KEY (Item_id) REFERENCES item (Item_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE billing(
Bill_id int (4) UNSIGNED NOT NULL AUTO_INCREMENT,
Card_num VARCHAR (16) NOT NULL,
Expiry VARCHAR (10) NOT NULL,
Sec_code int (3) NOT NULL,
PRIMARY KEY (Bill_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE customer(
Cust_id int (4) UNSIGNED NOT NULL AUTO_INCREMENT,
C_name VARCHAR (50) NOT NULL,
C_address VARCHAR (50) NOT NULL,
C_city VARCHAR (50) NOT NULL,
C_country VARCHAR (50) NOT NULL,
Bill_id int (4) UNSIGNED NOT NULL,
Telephone VARCHAR (20) NOT NULL,
PRIMARY KEY (Cust_id),
FOREIGN KEY (Bill_id) REFERENCES billing (Bill_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ordertable(
Order_id int (4) UNSIGNED NOT NULL AUTO_INCREMENT,
Cust_id int (4) UNSIGNED NOT NULL,
Cont_id int (4) UNSIGNED NOT NULL,
PRIMARY KEY (Order_id),
FOREIGN KEY (Cust_id) REFERENCES customer (Cust_id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (Cont_id) REFERENCES contents (Cont_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



